### ISSUE TITLE
Bubble issue

### ISSUE THREAD

**Issue by HGARZON** [mercadolibre/chico#1203] opened 2014-05-19 14:25 UTC
When defining a Bubble:

couponBubble = $.bubble({
    'content': msgDefMkt
}),

The component is working only with a subscription to an event. Otherwise, doesn't work :(

For example:

couponBubble.on('show', function() {
    this.refreshPosition({
        'reference': $('#couponCode')
    });
})

**Comment by atma** [comment] 2015-05-28 15:57
@HGARZON What kind of problem do you have? Can you provide more information please? Is the reference element exist and visible?

Cannot reproduce.

**Comment by atma** [comment] 2015-11-03 12:21
@HGARZON Any news?

**Comment by battaglr** [comment] 2017-03-21 13:11
@HGARZON, do you remember the specifics of this issue? Is this related to the *Bubble* not refreshing its position?

**Comment by HGARZON** [comment] 2017-03-21 18:00
Yes, it seems that the bubble position, if something changes on the DOM, only will change if we call the refreshPosition method.

**Comment by battaglr** [comment] 2017-03-21 18:11
@HGARZON, thanks! I'll re-label this as "feature request" instead of a "bug", since what you describe is the expected behaviour —but most certainly not the ideal.

**Comment by battaglr** [comment] 2017-07-26 23:04
I'll close this, since to automatically update the Bubble position we should add a `MutationObserver`, an `Event` or any other mechanism to identify if the DOM has changed. Sadly that's not aligned with the project's current objectives.

By using the [`refreshPosition()`](http://chico.mercadolibre.com/api-doc/2.0.11/ui/ch.validation/) method this could be implemented in specific projects if necessary.

**Closed by battaglr** 2017-07-26 23:04 UTC
Labels: feature request
