### ISSUE TITLE
Carousel: Pagination is always created

### ISSUE THREAD

**Issue by llinares** [mercadolibre/chico#1197] opened 2014-04-15 15:08 UTC
It never checks for `true` or `false`:
```js
if (this._options.pagination !== undefined) { this._addPagination(); }
```

It actually checks for boolean on arrows:
```js
if (this._options.arrows !== undefined && this._options.arrows !== false) { this._addArrows(); }
```

**Comment by atma** [comment] 2015-05-27 13:13
Duplicate of #1241. Was resolved in #1242

**Closed by atma** 2015-05-27 13:13 UTC
Labels: Bug
